script:
  - npm install linteverything@latest
  - printf "module.exports={ignore:['node_modules','package-lock.json','.git','.travis.yml'],verbose:true};" > .linteverythingrc.js
  - node ./node_modules/linteverything/bin/linteverything.js
  - node main.js
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git status
  - git commit -am "Travis build ${TRAVIS_BUILD_NUMBER}"
  - git status
  - git remote add tmp https://${GITHUB_TOKEN}@github.com/eleves-ig2i/ig2i-meta.git > /dev/null 2>&1
  - git remote -v
  - git branch -av
  - git checkout master
  - git push tmp master
  - git checkout -b yolo
  - git push tmp yolo
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
